export const case2 = [
  {
    company: "오뚜기_삼남공장",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "EnMS",
    bs_info: "2023EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "한국로스트왁스",
    year: 2024,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "렉셈",
    year: 2024,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "폴",
    year: 2024,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "넥센타이어_창녕",
    year: 2024,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
];
