export const case4 = [
  {
    company: "동은단조 펌프제어",
    year: 2022,
    img_url: "/asset/img/dongeun.jpg",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2022공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대불산단 1차 공압기제어",
    year: 2023,
    img_url: "/asset/img/daebul.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2023공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "신흥오토모티브 공압기제어",
    year: 2023,
    img_url: "/asset/img/sinheongauto.jpg",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2023공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대불산단 2차 공압기제어",
    year: 2024,
    img_url: "/asset/img/daebul.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2024공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "SK오션플랜트",
    year: 2025,
    img_url: "/asset/img/skoceanplant.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2025공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
];
