export const case3 = [
  {
    company: "한국전기",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "진주햄",
    year: 2023,
    img_url: "/asset/img/jinjuham.jfif",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대균",
    year: 2023,
    img_url: "/asset/img/daeguen.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "세화산업",
    year: 2023,
    img_url: "/asset/img/sewha.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "세영",
    year: 2024,
    img_url: "/asset/img/seyoung.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "인탑스",
    year: 2024,
    img_url: "/asset/img/intops.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "KRM",
    year: 2024,
    img_url: "/asset/img/krm.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "ENK",
    year: 2024,
    img_url: "/asset/img/enk.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
];
