export const case1 = [
  {
    company: "조광요턴",
    year: "~2022",
    img_url: "/asset/img/jogwang.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "넥센타이어_양산",
    year: "~2022",
    img_url: "/asset/img/nexen_yangsan.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "면사랑",
    year: "~2022",
    img_url: "/asset/img/meonsarang.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동은단조 밀양공장",
    year: "~2022",
    img_url: "/asset/img/dongeun.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "영엽",
    year: "~2022",
    img_url: "/asset/img/youngyup.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "태안오토텍",
    year: "~2022",
    img_url: "/asset/img/tean.avif",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "영흥",
    year: "~2022",
    img_url: "/asset/img/youngheong.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동화정밀",
    year: "~2022",
    img_url: "/asset/img/dongwha.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "정암산업",
    year: "~2022",
    img_url: "/asset/img/joengam.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동양철관",
    year: "~2022",
    img_url: "/asset/img/dongyangchul.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "파인트리포스마그네슘",
    year: "~2022",
    img_url: "/asset/img/pinetree.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)동양",
    year: 2023,
    img_url: "/asset/img/dongyang.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)에스앤더블유",
    year: 2023,
    img_url: "/asset/img/s&w.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)신흥오토모티브",
    year: 2023,
    img_url: "/asset/img/sinheongauto.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)신흥SEC",
    year: 2023,
    img_url: "/asset/img/sinheongsec.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)삼화제지",
    year: 2023,
    img_url: "/asset/img/samwha.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)건화공업",
    year: 2023,
    img_url: "/asset/img/gunwha.jpg",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)디엠산업",
    year: 2023,
    img_url: "/asset/img/dm.jfif",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)서연이화",
    year: 2023,
    img_url: "/asset/img/seoyeon.jfif",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
];

// ------------------------------------------------------

export const case2 = [
  {
    company: "오뚜기_삼남공장",
    year: 2023,
    img_url: "/asset/img/oddugi.jpg",
    id: "",
    bs_title: "EnMS",
    bs_info: "2023EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "넥센타이어_창녕",
    year: 2024,
    img_url: "/asset/img/nexen_changyoung.jpg",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "한국로스트왁스",
    year: 2024,
    img_url: "/asset/img/lostwacs.jpg",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "렉셈",
    year: 2024,
    img_url: "/asset/img/recsem.jpg",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "폴",
    year: 2024,
    img_url: "/asset/img/pole.jpg",
    id: "",
    bs_title: "EnMS",
    bs_info: "2024EnMS",
    desc: "<div>…</div><span>…</span>",
  },
];

// ----------------------------------------------------------

export const case3 = [
  {
    company: "진주햄",
    year: 2023,
    img_url: "/asset/img/jinjuham.jfif",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "KRM",
    year: 2024,
    img_url: "/asset/img/krm.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "ENK",
    year: 2024,
    img_url: "/asset/img/enk.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대균",
    year: 2023,
    img_url: "/asset/img/daeguen.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "세화산업",
    year: 2023,
    img_url: "/asset/img/sewha.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "세영",
    year: 2024,
    img_url: "/asset/img/seyoung.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "인탑스",
    year: 2024,
    img_url: "/asset/img/intops.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2024스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "한국정기",
    year: 2023,
    img_url: "/asset/img/koreajungi.jpg",
    id: "",
    bs_title: "스마트생태공장",
    bs_info: "2023스마트생태공장",
    desc: "<div>…</div><span>…</span>",
  },
];

// --------------------------------------------------------

export const case4 = [
  {
    company: "SK오션플랜트",
    year: 2025,
    img_url: "/asset/img/skoceanplant.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2025공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "신흥오토모티브 공압기제어",
    year: 2023,
    img_url: "/asset/img/sinheongauto.jpg",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2023공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대불산단 1차 공압기제어",
    year: 2023,
    img_url: "/asset/img/daebul.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2023공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "대불산단 2차 공압기제어",
    year: 2024,
    img_url: "/asset/img/daebul.webp",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2024공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동은단조 펌프제어",
    year: "~2022",
    img_url: "/asset/img/dongeun.jpg",
    id: "",
    bs_title: "공기압축기통합제어시스템",
    bs_info: "2022공기압축기통합제어시스템",
    desc: "<div>…</div><span>…</span>",
  },
];
