export const case1 = [
  {
    company: "동은단조 밀양공장",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "영엽",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "태안오토텍",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "면사랑",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "넥센타이어_양산",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "영흥",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동화정밀",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "정암산업",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "조광요턴",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "동양철관",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "파인트리포스마그네슘",
    year: ~2022,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "~2022FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)동양",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)에스앤더블유",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)신흥오토모티브",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)신흥SEC",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)삼화제지",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)건화공업",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)디엠산업",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
  {
    company: "(주)서연이화",
    year: 2023,
    img_url: "/asset/img/.png",
    id: "",
    bs_title: "FEMS",
    bs_info: "2023FEMS",
    desc: "<div>…</div><span>…</span>",
  },
];
